name: CI Pipeline

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: algomachine007
          DOCKER_PASSWORD: nYjCScWn6WhhN3@
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t algomachine007/cicd-pipeline:latest .
      - name: Push to Dockerhub
        run: docker push algomachine007/cicd-pipeline:latest
